//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shekelTest_Gitit_Luria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shekelTestEntities : DbContext
    {
        public shekelTestEntities()
            : base("name=shekelTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<FactoriesToCustomer> FactoriesToCustomers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
    }
}
